---
- name: Create users
  hosts: all
  become: yes
  tasks:
    - name: Ensure five users are present
      user:
        name: "{{ item }}"
        state: present
      loop:
         - dev_user
         - qa_user
         - prod_user
         - prod_user2
         - prod_user3

