---
- name: Output facts within a playbook
  hosts: all
  tasks:
    - name: Ensure httpd package is present
      yum:
        name: httpd
        state: latest
      register: http_results

    - debug:
        var: http_results
#    - name: Restart httpd 
#      service:
#        name: httpd
#        state: restart
#      when: httpd_results.changed
