---
- name: Output facts within a playbook
  hosts: all
  tasks:
  - name: Prints Ansible facts
    debug:
      msg: "{{ ansible_fqdn }}"

  - name: Prints Ansible facts
    debug:
      var: ansible_fqdn
