---
- name: Create users
  hosts: all
  become: yes
  tasks:
    - name: Ensure three users are present
      user:
        name: "{{ item }}"
        state: present
      loop:
        "{{ username }}" 


