---
- name: Install vsftpd on ftpservers
  hosts: all
  become: yes
  tasks:
    - name: Install FTP server when host in ftpserver group
      when: inventory_hostname in groups["ftpserver"]
      yum:
        name: vsftpd
        state: latest
