---
- name: launch roles
  hosts: all
  become: yes
  pre_tasks:
    - debug:
        msg: 'Beginning web server configuration.'

  roles:
    - role1

  post_tasks:
    - debug:
        msg: 'Web server has been configured.'
